[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = "npx prisma generate",


[start]
cmd = [
  "npx prisma migrate deploy",
  "node prisma/seedAdmin.js",
  "node server.js"
]

[variables]
NODE_ENV = "production"
